### ISSUE TITLE
Initiative Tracker

### ISSUE THREAD

**Issue by shadow7412** [kakaroto/Beyond20#409]
Synchronize the state of the DDB initiative tracker to VTTs.

# Core Requirements

* [X] The initiative score entered in DDB should replicate to the relevant VTT.
* [ ] VTT entered intiatives (particularly those by players, either via this extension or manually) should replicate to DDB.
* [X] Moving to the next unit's turn should be synchronised such that the combat can be progressed from ~either VTT or~ DDB.
* [X] Undo feature in DDB should be honored (whatever that does)

# Bonus Requirements

* ~HP bars on relevant token should be updated when tracking damage in DDB (and possibly vice versa) particularly for enemies.~ (not enough information to reliably link token with character, especially with monsters)
* ~Changing the HP of a token in the VTT should replicate back to the DDB tracker.~ (as above)
* [ ] Reduction to 0hp should cause a marker to appear on the token, to clearly show the creature is out of the fight.

**Comment by shadow7412** [comment]
```javascript
$(".combatant-card.in-combat").map((i, x) => [
    $(".combatant-summary__name", x).text(),
    $(".combatant-card__initiative-value", x).text(),
    $(x).hasClass("is-turn"),
])
```

This snippet extracts the names and initiative value of all players in the combat, and whether it's currently their turn - which is more or less all of the information we'd need from DDB.

**Comment by hypergig** [comment]
I would pay for this feature. Also, most folks click the beyond20 initiative button in DDB, which spits it to the VVT, that should somehow synchronize back to my encounter running and the VVT trackers.

I can't tell you how many times I accidentally closed out the tab on my encounter losing everyone's initiative... it would be great if those backfilled or there was a button that read them from the beyond20 chat tables.

I would put a bounty on this feature, honestly It would save a ton of time

**Comment by shadow7412** [comment]
I've started playing with the concept - I'm about 60% through a rough prototype which syncs the DDB tracker to Roll 20.

I've mentioned capturing initiative scores already, but reviving an accidentally refreshed tracker is an interesting idea worth considering. It's not hard to imagine that happening. Of course, some data will be lost (such as what turn we're up to) but getting the initiative scores back should be painless enough...

**Comment by hypergig** [comment]
Especially if they are already in the chat.. and came from the beyond20 in the first place

**Comment by Daekesh** [comment]
How would this work with the "hidden" entries on R20's initiative tracker? To be fair, I don't know if they are actually hidden, but when I roll initiative for a token on the gm layer, it appears in a darker text and I'm assuming the players either can't see it or don't know the name. I should probably get around to asking them!

**Comment by shadow7412** [comment]
I'm not sure. Chances are the initial implementation won't handle that case specifically - which means it might work, but it might not. The safest bet probably would be to leave all units public.

It's a very reasonable enhancement for after the basics work though.

**Comment by shadow7412** [comment]
@hypergig and @Daekesh - just letting you know that the first iteration of this has made it into the development build, so if you want to try this out, check out the instructions on the readme. If you'd rather be patient, I wouldn't be surprised if it was released soon. Only the DM needs to do this, no other players need the dev version for this to work.

Just some expectation setting though;

*  This version only works sends data from the tracker to roll 20. So you'll need to enter player initiatives into the tracker yourselves. I'll be looking into a way to address this next.
* As DDB has no support for hidden units (if I'm wrong, tell me) there's no real way to implement this at the moment.
* You must make all changes (including progressing the combat) from DDB tracker - any changes made in roll 20 (such as combat progression, hiding or adding units etc) will be overwritten the next time.

Anyway, let me know if you find any issues.

**Comment by kakaroto** [comment]
> If you'd rather be patient, I wouldn't be surprised if it was released soon.
Yep, just released 2.1.1 which includes this feature.

Keeping this issue open until implementation for Foundry VTT is also added (and might need to think of ways to do it for Discord as well)

**Comment by hypergig** [comment]
Initial feedback:

I love it.

I think it came out great, it was extremely helpful and the players loved it. I am not sure what other folks do but some of my players roll physically so I have to enter their numbers in anyway, and I do so in the DDB tracker. The biggest issue I have is beyond20 doesn't save any encounter state, so accidentally closing the tab OR spanning an encounter between multiple sessions ruins my life and sends me into a desk flipping range. For me, state saving is the primary reason to back-fill and re-synchronize state between the two systems, as roll20 does save state.

The only other nit picky thing I would suggest is to not automatically open the roll20 tracker, if that is even possible. I like my players guessing their ordering in initiative, at least for the first round. I would pop it open later when it makes sense.

And this isn't your issue too much, but getting familiars in there would be nice... but the character adder in beyond20 is very cumbersome and until that is fixed, it doesn't make sense for you to address it on your end.

Overall, very pleased, good work!

**Comment by cgplayer2000** [comment]
I prefer the turn tracker to open automatically.  My players like to move quickly, and they can read the numbers coming in on the chat window.  There’s enough going on at the start of combat, that having the turn tracker open automatically and sort automatically works best for me.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by shadow7412** [comment]
@hypergig thanks for the feedback - glad you like it :)

The lack of state saving is pretty annoying - but unfortunately is probably something that needs to be sorted on the DDB side of things. If you haven't already filed an issue with DDB, it'd be a good idea. The good news is that Beyond20 doesn't sync until the combat starts - meaning that you could manually enter the initiative information from roll 20. The manual part sucks, but at least you shouldn't lose anything.

As for not opening the tracker by default - you could turn off syncing (using the quick settings menu) before starting the combat, then turning it on when you're ready for players to see the tracker. Give this is a try and see if it's enough.

As for familiars - you could add an extra "character" to your campaign that represents the familiar. That way it'll automatically appear, assuming you have your campaign linked to the encounter.

If you have any further feedback or questions - it might be best to jump onto the beyond 20 discord.

**Comment by hypergig** [comment]
That is great advice, thanks @shadow7412 

>  you could add an extra "character" to your campaign 

Yeah I did this for a while but it made calculating experience much harder than it needed to be, I just ask the player to share the same init with their familiar.. which isn't right because the familiar has a much better init bonus then he has. I am hoping DDB puts more work into the encounter runner, it has quickly became one of my most depended on tools.

Clicking on baddy right in the init order, then via beyond20 clicking saves and attacks has sped up my combat by 500%. Esp with DDB backing all the monster blocks, it's a total game changer.

Out of curiosity have they approach the project for acquisition? Sorta a no brainer to at the very least, fund you folks if not offer you full time jobs on their payroll to maintain this project.

**Comment by shadow7412** [comment]
> Out of curiosity have they approach the project for acquisition?

It's a bit off-topic for this issue - and it's not my project. It's @kakaroto's. I've only contributed to it. In either case, the answer would have to be a "no". If they had, they would presumably also give us better ways to access the information on the page then scraping it like we currently do, and we'd actually get warning before they broke something rather than having to race to fix it while being pummeled with duplicate support requests.

Both he and I do have means to receive donations, but you're better off talking to us on discord about that if you're interested. This issue isn't the place for it, and for the sake of keeping this issue relevant, further unrelated discussion will probably be removed. Thanks for understanding.

**Comment by kakaroto** [comment]
Note: while I wasn't approached for acquisition by D&D Beyond (I do get people wanting to throw money my way to add ads or search bars or tracking crap into the extension, which I all ignore), and while we did get some breaking changes recently that made me scramble to get a fixed release out asap. Those things happen and are not indicative of D&D Beyond not being appreciative of Beyond20. It has been mentioned by Adam more than once in their official dev updates, and I have been approached by their dev team to give me advance notice for some breaking changes (I had access to the alpha sheet v3, and digital dice before it went to alpha).
The recent break was unfortunate and unexpected, and it was minor enough that I don't think anyone expected it to cause Beyond20 to break, or I would have probably had advance notice on it.

**Comment by kakaroto** [comment]
Considering that too many people get their Roll20 combat tracker wiped by this feature when they don't expect it, and that rare are those who name their monsters with the same name as in DNDB (The "(A)", and "(B)" suffixes), and too many of those who fail to find the option to turn it off, I feel like this option should became an always-ask.
By having it ask the user once "Do you want to sync this encounter to the Roll20 combat tracker? Note: all tokens need to have exactly matching names in order to have their HP mapped and be invisible for GM layer tokens.", it would avoid all these problems.
This would also allow GMs to decide when to use the feature without getting surprises mid-game. Having it ask once per encounter is not so bad (compared to an "always ask" on every roll). Reloading the page would make it ask again if the GM changes their mind.
What do you think of the proposal ?

**Comment by shadow7412** [comment]
I see the merit... though I'm not sure how fond I am of the idea of making the user do another click. Especially when I can imagine the kinds of users that have this issue just clicking through it and then have the exact problem either due to being used to clicking yes (but not meaning to for this specific combat) or being the kind who doesn't read these kinds of confirmations anyway. "It will avoid all these problems" is highly optimistic 😛 

The other feedback I've received is the desire to start a combat "blind", but make the tracker public after a certain condition (eg, the secret enemy is revealed, the first round has elapsed, the enemy's name is known, etc). If we're going with a confirmation, we're also probably going to want a way to give the OK after the combat has begun too.

**Comment by shadow7412** [comment]
Would it be easier to make that option appear on the actual page? That way there isn't an extra click, but GMs can toggle it on and off (persistently) as required.

That doesn't give them the extra hints about mapping the token of course...

**Comment by kakaroto** [comment]
- The cool thing is, if the user doesn't read and clicks, then it's their fault and we can't be blamed.. now Beyond20 does it on its own so they blame me :P
- "It will avoid all these problems" == "They won't be whining about it to me", but yeah, someone will probably whine about having to click ok, lol.
- Can't start "blind", there is no way of making a combatant on roll20 invisible unless it's linked to a token which is in the GM layer.
- I really like the idea of having a button to sync on the encounter page. Something at the top, a big Beyond20 icon with "Sync Combat Tracker" and it would be a sort of togglable button to enable/disable it, and on hover, it could show the warning as a tooltip. 👍

**Comment by shadow7412** [comment]
Point 3: By that I mean it doesn't sync at all to the players. [This message](https://github.com/kakaroto/Beyond20/issues/409#issuecomment-658781439) is the one I was thinking of when I said that.

Point 4: Me too. Do we have a way to put setting sliders on the UI already?

**Comment by kakaroto** [comment]
3: Ah ok, then yeah the button solves that too anyway!
4: brain is toast, not sure. I wasn't thinking of a slider, but an actual button, like the "Display in VTT" but instead "Sync with VTT" and have it appear depressed or change color or something once it's in sync mode. A slider has the implication that it's changing a setting and that it would be saved between reloads, I'd prefer to have the sync be a "you must click it to initiate the sync" with having it be a button

**Comment by shadow7412** [comment]
4. That's exactly what I'm trying to avoid - because it's another click for players who actively use the tracker. Tomato tomata for whether it's a slider or button, but I'd like it to simply replicate the setting I think the users probably fit into one of 3 groups;

1. Those who don't want to use the tracker. These people would want it off always.
2. Those who use the tracker. These people would want it on always, or perhaps turn it off for an exception encounter to then turn it back on.
3. Those who want to 'hide' the first round of combat on a regular basis. I've heard of this idea literally once and I'm not convinced many people fit into this group.

By making the option clear on the UI, it should serve as as reminder before one starts the combat, especially if we can get the option to sit next to the start/next buttons on the actual tracker. This should satisfy all groups.

But I really can't imagine people wanting to be nagged every single combat, whether it be by dialogues or players...

**Comment by protoclown11** [comment]
Came here to ask if we could add an option to turn off populating the Roll20 tracker from the DDB combat tracker when starting the encounter. Had an encounter set up last night where I had extra enemies hidden that would appear during the encounter, but the auto population of the Roll20 tracker showed everyone how many enemies there were, even though they couldn't see them yet. So much for surprise. :) Scanned the milestone listing and didn't see this option, is it planned?

**Comment by Aeristoka** [comment]
> Came here to ask if we could add an option to turn off populating the Roll20 tracker from the DDB combat tracker when starting the encounter. Had an encounter set up last night where I had extra enemies hidden that would appear during the encounter, but the auto population of the Roll20 tracker showed everyone how many enemies there were, even though they couldn't see them yet. So much for surprise. :) Scanned the milestone listing and didn't see this option, is it planned?

Literally already an option (under "More Options"):
![image](https://user-images.githubusercontent.com/7988297/109536274-c71b8380-7a7a-11eb-978c-481bffc07074.png)
